version: "3"

services:
  bot:
    build: .
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - REDIS_PASSWORD=my-password