version: "3"

services:
  bot:
    build: .
    environment:
        TELEGRAM_TOKEN: ${API_BOT}
        CLIENT_TOKEN: ${API_CLIENT}
        ASSISTANT_ID: ${ID_ASSISTANT}
        AMPLITUDE_API: ${API_AMPLITUDE}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_NAME: ${DB_NAME}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379" # Порт Redis